MODULE COST_MODULE
USE ORBITAL_FUNCTIONS
USE MATH_MODULE
USE CONSTANTS
IMPLICIT NONE
 ! THIS MODULE MINIMIZES AND EARTH-SATURN TRANSFER
CONTAINS



SUBROUTINE COST(N_DOUBLE, N_INT, N1, N2, X, CHROM_INT, FITNESS, ARRAY, G_CON, NCON)
IMPLICIT NONE
INTEGER, INTENT(IN) :: N_DOUBLE, N_INT, N1, N2, CHROM_INT(N_INT), NCON
DOUBLE PRECISION, INTENT(IN) :: X(N_DOUBLE), ARRAY(N1,N2)
DOUBLE PRECISION, INTENT(INOUT) :: FITNESS, G_CON(NCON)


DOUBLE PRECISION :: OE(6), R1(3), V1(3), R2(3), V2(3), V(6), V1_INF(3), V1_INF_MAG

DOUBLE PRECISION :: C3_LIM, DV1, DV2, DVF, DT, SV(6), VF_INF(3)!, V_INF_IN(3), V_INF_OUT(3)
DOUBLE PRECISION :: ARR_PEN, VP1, VP2, RPL, eF, rpf, GA_CHECK, asteroid(N1,N2)
INTEGER :: PL, PF, NGA, I, K, OT, NREV, n11, n22
!INTEGER, ALLOCATABLE :: P(:)
DOUBLE PRECISION :: DV_GA(CHROM_INT(2)), G(CHROM_INT(2)), R_P(CHROM_INT(2)), V_INF_IN(CHROM_INT(2),3)
DOUBLE PRECISION :: V_INF_OUT(CHROM_INT(2),3), J(CHROM_INT(2)+2), LENGTH_PENALTY, TOF_TOT
INTEGER ::  P(CHROM_INT(2)+1) 

OT=1
NREV=0
!N11=N1
!N22=N2
!ASTEROID=ARRAY
NGA=CHROM_INT(2)
!WRITE(*,*) "NGA", NGA
PL=CHROM_INT(1)
RPF=80330.D0
eF=.98D0



P(NGA+1)=CHROM_INT(3)
P(1:NGA)=CHROM_INT(4:NGA+3)





J(1)=X(1)
DO I=2,NGA+1,1
    J(I)=X(I)+J(I-1)
END DO
J(NGA+2)=X(N_DOUBLE)+J(NGA+1)


! DEPARTURE PHASE

CALL PLAN_ELEM(J(1), PL,ARRAY,N1,N2,OE)
SV=OE2SV(OE(1),OE(2),OE(3),OE(4),OE(5),OE(6))
R1=SV(1:3) 
V1=SV(4:6)
CALL PLAN_ELEM(J(2), P(1),ARRAY,N1,N2,OE)
SV=OE2SV(OE(1),OE(2),OE(3),OE(4),OE(5),OE(6))
R2=SV(1:3)
V2=SV(4:6)

DT=(J(2)-J(1))*86400.D0
!CALL lambert_GOODING(R1,R2,DT,OT,V)
CALL lambert_sun(R1,R2,DT,OT,V)
!IF(ISNAN(NORM(V)) .or. v(1).gt.9.9d11)THEN
!    call LAMBERT_battin(R1,R2,DT,OT, V)
!END IF
V1_INF=V1-V(1:3)
V1_INF_MAG=NORM(V1_INF)


R1=R2
V1=V2
V_INF_IN(1,1:3)=V(4:6)-V1

!GRAVITY ASSISTS
DO I=1,NGA,1
    DT=(J(I+2)-J(I+1))*86400.D0
    CALL PLAN_ELEM(J(I+2), P(I+1),ARRAY,N1,N2,OE)
    SV=OE2SV(OE(1),OE(2),OE(3),OE(4),OE(5),OE(6))  
    R2=SV(1:3)
    V2=SV(4:6)
    !CALL lambert_GOODING(R1,R2,DT,OT,V)
    CALL lambert_sun(R1,R2,DT,OT,V)
    !IF(ISNAN(NORM(V)) .or. V(1).gt.9.9d11)THEN
    !    CALL LAMBERT_BATTIN(R1,R2,DT,OT, V)
    !END IF
    V_INF_OUT(I,1:3)=V(1:3)-V1
    IF (I.EQ.NGA) THEN
        VF_INF=V(4:6)-V2
    ELSE
        V_INF_IN(I+1,1:3)=V(4:6)-V2
    END IF
    V1=V2
    R1=R2
END DO


! TEST FOR POSSIBLE RESONANT ORBITS AROUND THE EARTH OR VENUS
!DO I=1,NGA,1
!    !RESONANT_ORBIT(T1,T2,P1,P2, V1_INF_IN,V2_INF_OUT, V1_INF_OUT, V2_INF_IN)
!    IF (I.GE.1 .and. i.lt.nga) THEN
!        IF(P(I).EQ.3 .AND. P(I+1).EQ.3) THEN
!            IF(ABS(J(I+2)-J(I+1)-2.D0*365.242189D0).LE.5.D0) THEN
!                CALL RESONANT_ORBIT(J(I+1),J(I+2),P(I),P(I+1), V_INF_IN(I,1:3),V_INF_OUT(I+1,1:3), &
!                                   V_INF_OUT(I,1:3), V_INF_IN(I+1,1:3))
!            END IF
!        ELSE IF (P(I).EQ.2 .AND. P(I+1).EQ.2) THEN
!            IF(ABS(J(I+2)-J(I+1)-2.D0*224.7D0).LE.5.D0) THEN
!                CALL RESONANT_ORBIT(J(I+1),J(I+2),P(I),P(I+1), V_INF_IN(I,1:3),V_INF_OUT(I+1,1:3), &
!                                   V_INF_OUT(I,1:3), V_INF_IN(I+1,1:3))
!            END IF
!        END IF
!    END IF 
!END DO
!WRITE(*,*) "CALCULATING GA'S"
DO I=1,NGA,1
    CALL GA_MGA(V_INF_IN(I,1:3), V_INF_OUT(I,1:3), P(I), R_P(I), DV_GA(I), G(I))
    !WRITE(*,*) "DV_GA", I, DV_GA(I)
END DO


!ARRIVAL
!WRITE(*,*) "VF_INF", NORM(VF_INF)
CALL ARRIVAL_MGADSM(P(NGA+1), eF, RPF, VF_INF, dVF)


C3_LIM=18.0693856561d0
RPL=6378.137D0+300.D0
DV1=SQRT(C3_LIM+2.D0*MU_PLANET(PL)/RPL)
DV2=SQRT(V1_INF_MAG**2+2.D0*MU_PLANET(PL)/RPL)
IF (V1_INF_MAG.GT.SQRT(C3_LIM)) THEN
    ARR_PEN=DV2-DV1
    
!ELSE IF (V1_INF_MAG.LT.SQRT(2.D0)) THEN
!    ARR_PEN=SQRT(2.D0)-V1_INF_MAG
ELSE
    ARR_PEN=0.D0
END IF

!Penalize flights longer than 10 years
TOF_TOT=J(NGA+2)-J(1)
LENGTH_PENALTY=0.D0
!IF (TOF_TOT.GT.(365.25D0*15.D0)) THEN
!    LENGTH_PENALTY=0.1D0*(TOF_TOT-365.25D0*15.D0)
!END IF

FITNESS=ARR_PEN+SUM(DV_GA)+SUM(G)+DVF+LENGTH_PENALTY




! CHECK TO SEE THAT THIS FLYBY ORDER HASN'T ALREADY BEEN OPTIMIZED
do i=1,n1,1
    !WRITE(*,*) I
    NGA=NINT(ARRAY(I,2))
    IF (NGA.GT.0) THEN
        GA_CHECK=0.D0
        DO K=1,NGA,1
            GA_CHECK=GA_CHECK+ABS(ARRAY(I,3+K)-DBLE(P(K)))

        END DO
    
        IF (GA_CHECK.LT.1.D-8 .AND. FITNESS.GT.ARRAY(I,N2)) THEN
            !WRITE(*,*) GA_CHECK, FITNESS
            FITNESS=1.D30
        
        END IF
    END IF

end do
nga=chrom_int(2)
!MAKE SURE SOLUTIONS AREN'T PICKED THAT GO TO AN OUTER PLANET AND BACK TO AN INNER PLANET
DO I = 1,NGA-1,1
    !WRITE(*,*) I, P(I)
    !WRITE(*,*) P(I)
    IF (P(I).EQ.5) THEN
        FITNESS=1.D30
        !WRITE(*,*) "VIOLATED"
    END IF
END DO

!DEALLOCATE (DV_GA, G, R_P,V_INF_IN, V_INF_OUT, P, J)
if (fitness.gt.9.9d7 .or. isnan(fitness) ) fitness=1.d30
END SUBROUTINE COST


END MODULE COST_MODULE
