PROGRAM DRIVER
USE CONSTANTS
USE MATH_MODULE
USE ORBITAL_FUNCTIONS
USE OPTIMIZATION_MODULE
use omp_lib
IMPLICIT NONE

INTEGER :: N_POP, N_GEN, N_INT, N_DOUBLE, N_RUNS, N1,N2, NCON, ITER_MAX_MBH, ITER_MAX_NLP, N_CON
INTEGER, ALLOCATABLE :: INTEGER_UPPER(:)
INTEGER, ALLOCATABLE :: INTEGER_LOWER(:)
DOUBLE PRECISION :: P_CROSS, P_REP,P_MUT 
DOUBLE PRECISION, ALLOCATABLE :: DOUBLE_UPPER(:), DOUBLE_LOWER(:), INPUT_ARRAY(:,:)
CHARACTER(LEN=30) :: CROSSOVER_TYPE, MUTATION_TYPE, SELECTION_TYPE, OPTIMIZATION_TYPE

INTEGER, ALLOCATABLE :: INTEGER_RUN(:,:), CHROM_INT(:)
DOUBLE PRECISION, ALLOCATABLE :: MIN_RUN(:), AVG_RUN(:), DOUBLE_RUN(:,:), LAST_HALF_CHANGE(:)

INTEGER :: SEED,  COUNT1, COUNT2, RATE, I, J, MIN_LOC, IPRINT, COUNT, NGEN_CONVERGE
DOUBLE PRECISION :: TIME , FITNESS_INDV, TOL_CONVERGE, MAX_TIME
DOUBLE PRECISION, ALLOCATABLE :: FITNESS_AVG(:), FITNESS_MIN(:), DOUBLE_MIN(:,:), X0(:), X(:)
INTEGER, ALLOCATABLE :: INTEGER_MIN(:,:)

! PROBLEM SPECIFIC VARIABLES
INTEGER :: yi, mi, di, hi, mini, si
INTEGER :: yf, mf, df, hf, minf, sf
DOUBLE PRECISION :: J0, JF


!SEED FOR FIRST RANDOM NUMBER GENERATION
SEED=-54528542



!IF AN INPUT ARRAY OF INFORMATION NEEDS TO BE PASSED TO THE COST FUNCTION USE
!INPUT_ARRAY WHICH HAS A SIZE OF N1, N2



yi=2030
mi=1
di=1
hi=12
mini=0
si=0
J0=jdate(yi,mi,di,hi,mini,si)

yf=2039
mf=12
df=31
hf=12
minf=0
sf=0
Jf=jdate(yf,mf,df,hf,minf,sf)

!yi=1997
!mi=9
!di=14
!hi=12
!mini=0
!si=0
!J0=jdate(yi,mi,di,hi,mini,si)
!
!yf=1997
!mf=11
!df=14
!hf=12
!minf=0
!sf=0
!Jf=jdate(yf,mf,df,hf,minf,sf)


!PROBLEM INPUTS
P_CROSS=0.9D0
P_REP=1.D0-P_CROSS
P_MUT=0.5D0
N_POP=500
N_GEN=2500
N_INT=11
N_DOUBLE=10
N_CON=0
N_RUNS=1000
IPRINT=1
NGEN_CONVERGE=50
MAX_TIME=1000.D0
TOL_CONVERGE=1.D-5

N1=n_runs
N2=n_int+1
ALLOCATE(INPUT_ARRAY(N1,N2))
INPUT_ARRAY=0.D0
!MAXIMUM NUMBER OF ITERATIONS EACH NLP SOLVER CALL IS ALLOWED
ITER_MAX_NLP=100
! MAXIMUM NUMBER OF BAD SOLUTIONS ALLOWED WHEN THE MONOTONIC BASIN HOPPING OPTIMIZATION METHOD IS USED
ITER_MAX_MBH=5000


!OPTIMIZATION TYPES INCLUDE:
!   GEN - PURE GENETIC ALGORITHM OPTIMIZATION
!   HYB - HYBRID ALGORITHM THAT ITERATES ON THE COST FUNCTION WITH A TRADITIONAL 
!         NLP SOLVER
!   ALT - ALTERNATES 10 GENERATIONS OF PURE GENETIC ALGORITHM AND 10 GENERATIONS 
!         OF THE HYBRID ALGORITHM
OPTIMIZATION_TYPE="HYB_UNCMIN"
!OPTIMIZATION_TYPE="HYB_CONMIN"
!OPTIMIZATION_TYPE="GEN"

!OPTIMIZATION PARAMETERS TYPES
!CROSSOVER_TYPE="DOUBLE_POINT"
!CROSSOVER_TYPE="HEURISTIC"
CROSSOVER_TYPE="ARITHMETIC"
MUTATION_TYPE="UNIFORM"
SELECTION_TYPE="ROULETTE"

!ALLOCATE VARIABLE LIMIT ARRAYS HERE
ALLOCATE(INTEGER_LOWER(N_INT))
ALLOCATE(INTEGER_UPPER(N_INT))

ALLOCATE(DOUBLE_LOWER(N_DOUBLE))
ALLOCATE(DOUBLE_UPPER(N_DOUBLE))

integer_upper=5
!INTEGER INPUT BOUNDS
!LAUNCH PLANET
INTEGER_UPPER(1)=3
!NGA
INTEGER_UPPER(2)=8
!FINAL ARRIVAL PLANET
INTEGER_UPPER(3)=7
!GRAVITY ASSIST PLANETS
!INTEGER_UPPER(4)=5
!INTEGER_UPPER(5)=5
!INTEGER_UPPER(6)=5
!INTEGER_UPPER(7)=5
!INTEGER_UPPER(8)=5
!INTEGER_UPPER(9)=5
!INTEGER_UPPER(10)=5
!INTEGER_UPPER(11)=5


integer_lower=1
INTEGER_LOWER(1)=3
INTEGER_LOWER(2)=3
INTEGER_LOWER(3)=7
!INTEGER_LOWER(4)=1
!INTEGER_LOWER(5)=1
!INTEGER_LOWER(6)=1
!INTEGER_LOWER(7)=1
!INTEGER_LOWER(8)=1
!INTEGER_LOWER(9)=1
!INTEGER_LOWER(10)=1
!INTEGER_LOWER(11)=1


double_upper=5000.d0
!LAUNCH DATE
DOUBLE_UPPER(1)=JF
!INITIAL TOF
!DOUBLE_UPPER(2)=2500.D0
!DOUBLE_UPPER(3)=2500.D0
!DOUBLE_UPPER(4)=2500.D0
!DOUBLE_UPPER(5)=2500.D0
!DOUBLE_UPPER(6)=2500.D0
!DOUBLE_UPPER(7)=2500.D0
!DOUBLE_UPPER(8)=2500.D0
!DOUBLE_UPPER(9)=2500.D0
!TOF OF FINAL LEG
!DOUBLE_UPPER(n_double)=2500.D0


double_lower=25.d0
DOUBLE_LOWER(1)=J0
!DOUBLE_LOWER(2)=25.D0
!DOUBLE_LOWER(3)=25.0D0
!DOUBLE_LOWER(4)=25.0D0
!DOUBLE_LOWER(5)=25.0D0
!DOUBLE_LOWER(6)=25.0D0
!DOUBLE_LOWER(7)=25.0D0
!DOUBLE_LOWER(8)=25.0D0
!DOUBLE_LOWER(9)=25.0D0
!DOUBLE_LOWER(10)=25.0D0


!********************************************************************************************!
! START TIMER
CALL SYSTEM_CLOCK(COUNT1,RATE)

ALLOCATE(FITNESS_AVG(N_GEN), FITNESS_MIN(N_GEN))
ALLOCATE(INTEGER_MIN(N_GEN, N_INT))
ALLOCATE(DOUBLE_MIN(N_GEN, N_DOUBLE))
ALLOCATE(INTEGER_RUN(N_RUNS, N_INT), MIN_RUN(N_RUNS), AVG_RUN(N_RUNS))
ALLOCATE(DOUBLE_RUN(N_RUNS,N_DOUBLE), LAST_HALF_CHANGE(N_RUNS))
ALLOCATE(X0(N_DOUBLE), X(N_DOUBLE), CHROM_INT(N_INT))


count=integer_lower(2)-1

DO I=1,N_RUNS,1

    COUNT=COUNT+1
    INTEGER_LOWER(2)=COUNT
    IF (COUNT.GE.INTEGER_UPPER(2)) THEN
        COUNT=1
    END IF
    !
    !IF (INTEGER_LOWER(2).EQ.7) THEN
    !    INTEGER_LOWER(2)=2
    !END IF
    ! START GENETIC ALGORITHM
    !CALL GENETIC_DRIVER(N_POP, N_GEN, N_INT, N_DOUBLE, N1, N2, ITER_MAX_MBH, ITER_MAX_NLP, &
    !                N_CON, INTEGER_UPPER, INTEGER_LOWER, P_CROSS, P_REP,P_MUT, DOUBLE_UPPER, &
    !                DOUBLE_LOWER, INPUT_ARRAY, CROSSOVER_TYPE, MUTATION_TYPE, &
    !                SELECTION_TYPE, OPTIMIZATION_TYPE, SEED, FITNESS_MIN, FITNESS_AVG, &
    !                INTEGER_MIN, DOUBLE_MIN)

CALL GNLP_DRIVER(IPRINT, N_POP, N_GEN, N_INT, N_DOUBLE, N1, N2, ITER_MAX_NLP, &
    N_CON, INTEGER_UPPER, INTEGER_LOWER, P_CROSS, P_REP,P_MUT, DOUBLE_UPPER, &
    DOUBLE_LOWER, INPUT_ARRAY, CROSSOVER_TYPE, MUTATION_TYPE, &
    SELECTION_TYPE, OPTIMIZATION_TYPE, SEED, FITNESS_MIN, FITNESS_AVG, &
    INTEGER_MIN, DOUBLE_MIN, MAX_TIME, NGEN_CONVERGE, TOL_CONVERGE)
    
    CALL SYSTEM_CLOCK(COUNT2)
    TIME=DBLE(COUNT2-COUNT1)/DBLE(RATE)
    MIN_RUN(I)=FITNESS_MIN(N_GEN)
    
    DOUBLE_RUN(I,1:N_DOUBLE)=DOUBLE_MIN(N_GEN,1:N_DOUBLE)
    INTEGER_RUN(I,1:N_INT)=INTEGER_MIN(N_GEN,1:N_INT)
    input_array(I,1:n_int)=dble(integer_run(I,1:n_int))
    input_array(I,n_int+1)=min_run(i)
    !WRITE(*,*) INPUT_ARRAY(I,1:N2)
    WRITE(*,*) TIME, I!, MIN_RUN(I), INTEGER_RUN(I,1:N_INT), "CASSINI"!, DOUBLE_RUN(I,1:N_DOUBLE)
    OPEN(1,FILE='GENETIC_OUTPUT_URANUS.TXT',ACCESS='APPEND')
    WRITE(1,*) INTEGER_RUN(i,1:N_INT), MIN_RUN(I), DOUBLE_RUN(i,1:N_DOUBLE)
    close(1)
END DO

!GET TIME

CALL SYSTEM_CLOCK(COUNT2)
TIME=DBLE(COUNT2-COUNT1)/DBLE(RATE)

!MIN_LOC=MINLOC(MIN_RUN,1)

!WRITE(*,*) "THE BEST SOLUTION IS:"

!WRITE(*,*) MIN_RUN(MIN_LOC)
!write(*,*) double_run(min_loc,1:n_double)

!WRITE(*,*) "AVERAGE FITNESS: ", SUM(MIN_RUN)/DBLE(N_RUNS)
!WRITE(*,*) "50% CHANGE AVG:  ", SUM(LAST_HALF_CHANGE)/DBLE(N_RUNS)
!WRITE(*,*) "TOTAL RUN TIME   ", TIME
!WRITE(*,*) "CROSSOVER TYPE:  ", TRIM(CROSSOVER_TYPE)
!WRITE(*,*) "MUTATION  TYPE:  ", TRIM(MUTATION_TYPE) 

!OPEN(1,FILE='GENETIC_OUTPUT_MULTIPLE.TXT')!,ACCESS='APPEND')
!WRITE(1,*) "CROSSOVER TYPE:          ", TRIM(CROSSOVER_TYPE)
!WRITE(1,*) "MUTATION  TYPE:          ", TRIM(MUTATION_TYPE) 
!WRITE(1,*) "OPTIMIZATION TYPE:       ", TRIM(OPTIMIZATION_TYPE)
!WRITE(1,*) "TOTAL RUN TIME:          ", TIME
!WRITE(1,*) "CROSSOVER PROBABILITY:   ", P_CROSS
!WRITE(1,*) "REPRODUCTION PROBABILITY:", P_REP
!WRITE(1,*) "MUTATION PROBABILITY:    ", P_MUT
!WRITE(1,*) "POPULATION SIZE:         ", N_POP
!WRITE(1,*) "NUMBER OF GENERATIONS    ", N_GEN
!WRITE(1,*) "NUMBER OF GA RUNS:       ", N_RUNS
!WRITE(1,*) "*************************"
!WRITE(1,*) "THE BEST SOLUTION IS:"
!WRITE(1,*) MIN_RUN(MIN_LOC), INTEGER_RUN(MIN_LOC,1:N_INT), DOUBLE_RUN(MIN_LOC,1:N_DOUBLE)
!WRITE(1,'(F17.6, 4X)', ADVANCE='NO') MIN_RUN(MIN_LOC)
!DO J=1,N_INT
!    WRITE(1,'(I2, 4X)', ADVANCE='NO') INTEGER_RUN(MIN_LOC,J)
!END DO
!
!DO J=1,N_DOUBLE,1
!    IF( J.LT.N_DOUBLE) THEN
!        WRITE(1,'(F17.6, 4X)', ADVANCE='NO') DOUBLE_RUN(MIN_LOC,J)
!    ELSE
!        WRITE(1,'(F17.6, 4X)', ADVANCE='YES') DOUBLE_RUN(MIN_LOC,J)
!    END IF
!END DO 
!WRITE(1,*) "*************************"
!WRITE(1,*) "         "
!WRITE(1,*) "*************************"
!WRITE(1,*) "ALL OF THE SOLUTIONS ARE:"    
!WRITE(1,*) "*************************"
!
!DO I=1,N_RUNS,1
!    WRITE(1,*) MIN_RUN(I), INTEGER_RUN(i,1:N_INT), DOUBLE_RUN(i,1:N_DOUBLE)
!    !WRITE(1,'(F17.6, 4X)', ADVANCE='NO') MIN_RUN(I)
!    !DO J=1,N_INT
!    !    WRITE(1,'(I2, 4X)', ADVANCE='NO') INTEGER_RUN(I,J)
!    !END DO
!    !
!    !DO J=1,N_DOUBLE,1
!    !    IF( J.LT.N_DOUBLE) THEN
!    !        WRITE(1,'(F17.6, 4X)', ADVANCE='NO') DOUBLE_RUN(I,J)
!    !    ELSE
!    !        WRITE(1,'(F17.6, 4X)', ADVANCE='NO') DOUBLE_RUN(I,J)
!    !    END IF
!    !END DO 
!    !
!    !WRITE(1,'(A7)',ADVANCE='YES') TRIM(OPTIMIZATION_TYPE)
!END DO

!PERFORM CLEAN UP OPERATIONS HERE.  THIS ISN'T REQUIRED, BUT IT KEEPS THE INTEL ANALYZER HAPPY
DEALLOCATE(INTEGER_LOWER, INTEGER_UPPER, DOUBLE_LOWER, DOUBLE_UPPER)
DEALLOCATE(FITNESS_AVG, FITNESS_MIN, INTEGER_MIN, DOUBLE_MIN, INPUT_ARRAY)

END PROGRAM DRIVER
